name: Java CI to create and upload release on pull request
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  build-number: ${GITHUB_RUN_NUMBER}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # workaround for missing secret in fork PRs - see https://github.com/actions/checkout/issues/298
      # see https://github.com/rectorphp/rector/commit/d395e1c28b8e6a56711dcc2e10490a82965850e4
      -
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: 'maven'
      - run: mvn clean package -DskipTests
      - run: mkdir staging && mv target/minecraft-data-java-wrapper-1.0.0.jar target/minecraft-data-java-wrapper-${{ env.build-number }}.jar && cp target/*.jar staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
          retention-days: 1
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          automatic_release_tag: "${{ github.run_number }}"
          title: "Automated Build ${{ github.run_number }}"
          prerelease: true
          files: staging/*.jar
