name: Build and Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin' # Or any other JDK distribution that supports JDK 24

      - name: Build with Maven
        run: mvn clean package

      - name: Find JAR file
        id: find-jar
        run: |
          JAR_FILE=$(find target -name "*.jar" -not -name "*-sources.jar" -not -name "*-javadoc.jar")
          echo "JAR_FILE=$JAR_FILE" >> $GITHUB_OUTPUT

      - name: Upload JAR as release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.get-jar-path.outputs.JAR_FILE }}
          asset_name: ${{ steps.get-jar-path.outputs.JAR_FILE }}
          tag: ${{ github.ref_name }} # Using ref_name to get the tag without 'refs/tags/'
          overwrite: true
          body: "Release for ${{ github.ref_name }}" # You can customize this